# Generated by Django 4.2.5 on 2023-10-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
