# Generated by Django 4.2.5 on 2023-10-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userprofile_additional_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_in_designing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state_region',
        ),
    ]
