# Generated by Django 4.2.5 on 2023-10-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_comment',
        ),
    ]
