# Generated by Django 4.2.5 on 2023-10-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_fitnessservice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnessservice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='fitnessservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
